CiRent.WebUi/Controllers/PartialController.cs
using CiRent.BL.Concrete;
using CiRent.BL.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CiRent.WebUi.Controllers
{
    /// <summary>
    /// http://stackoverflow.com/questions/5095183/how-would-i-run-an-async-taskt-method-synchronously
    /// </summary>
    public class PartialController : Controller
    {
        // GET: Partial
        public PartialViewResult _CartModal()
        {
            return PartialView();
        }
        public PartialViewResult _ProfileModal()
        {
            return PartialView();
        }
        public  PartialViewResult _Categories(int id)
        {
            DataHandler c = new DataHandler();
            return PartialView(c.BindSideBarCategories(id).GetAwaiter());
        }
    }
}

CiRent.WebUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>

    @*@{ Html.RenderAction("_CartModal", "Partial"); }
    @{ Html.RenderAction("_ProfileModal", "Partial"); }*@
    
    <header>
        <div class="header-content">
            <div class="slogan-holder">
                <h1 class="company-name-label">CiRent</h1>
                <span class="company-name-label">Film equipment rental</span>
            </div>
            <form class="search-holder" action="~/Home/Search">
                <input class="search" type="text" name="text" />
                <button type="submit"><img src="~/Images/search.svg" alt="Search"></button>
            </form>
            <div class="profile-button-holder">
                <img src="~/Images/profile_img.jpg" alt="">
                <span>Profile Name</span>
                <button id="open_profile_modal">
                    <img src="~/Images/cog.svg" alt="">
                </button>
            </div>
            <div class="cart-holder">
                <button id="open_cart_modal" class="cart-button">
                    <span>10</span>
                </button>
                <span class="total-price">228322$</span>
            </div>
        </div><!-- header-content -->
        <div class="nav-holder">
            <ul class="menu nav-menu">
                <li class="menu-item"><a href="#">Home</a></li>
                <li class="menu-item"><a href="#">My orders</a></li>
                <li class="menu-item"><a href="#">About us</a></li>
                <li class="menu-item"><a href="#">Contacts</a></li>
            </ul>
        </div><!-- nav-holder -->
    </header>

    <div class="wrapper">
        <main>
            @RenderBody()
        </main>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>